services:
  saas_backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    depends_on:
      - saas_db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed &&
             python manage.py runserver 0.0.0.0:8000"

  saas_db:
    image: postgres:15
    environment:
      POSTGRES_DB: saas
      POSTGRES_USER: saas
      POSTGRES_PASSWORD: saas
    ports:
      - "5433:5432"
    volumes:
      - saas_postgres_data:/var/lib/postgresql/data

  saas_frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5174:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - saas_backend

volumes:
  saas_postgres_data:
