# Generated by Django 6.0.2 on 2026-02-10 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ownership",
            name="ownership_individual_requires_member",
        ),
        migrations.RenameIndex(
            model_name="familymember",
            new_name="memberships_user_id_3072f6_idx",
            old_name="memberships_f_user_id_8b8f60_idx",
        ),
        migrations.RenameIndex(
            model_name="familymember",
            new_name="memberships_user_id_289b6c_idx",
            old_name="memberships_f_user_id_d6f6b6_idx",
        ),
        migrations.RenameIndex(
            model_name="ownership",
            new_name="memberships_user_id_cd244c_idx",
            old_name="memberships_o_user_id_2f3efb_idx",
        ),
        migrations.AddConstraint(
            model_name="ownership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "individual"), ("member__isnull", False)),
                    models.Q(("kind", "shared"), ("member__isnull", True)),
                    _connector="OR",
                ),
                name="ownership_individual_requires_member",
            ),
        ),
    ]
