# Generated by Django 6.0.2 on 2026-02-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0002_remove_ownership_ownership_individual_requires_member_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnershipLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("asset", "Activo"), ("liability", "Pasivo")], max_length=16
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ownership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="memberships.ownership",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="ownershiplink",
            index=models.Index(
                fields=["user", "target_type", "target_id"], name="memberships_user_id_247f36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ownershiplink",
            index=models.Index(fields=["ownership"], name="memberships_ownersh_95cc7f_idx"),
        ),
        migrations.AddConstraint(
            model_name="ownershiplink",
            constraint=models.UniqueConstraint(
                fields=("user", "target_type", "target_id"), name="uniq_target_per_user"
            ),
        ),
    ]
