# Generated by Django 6.0.2 on 2026-02-19 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0007_saasaccessprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaasAuthAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event", models.CharField(max_length=64)),
                ("outcome", models.CharField(max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="saasauthauditevent",
            name="actor_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saas_auth_audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="saasauthauditevent",
            index=models.Index(fields=["created_at"], name="memberships_created_85056c_idx"),
        ),
        migrations.AddIndex(
            model_name="saasauthauditevent",
            index=models.Index(fields=["event", "created_at"], name="memberships_event_e89c20_idx"),
        ),
        migrations.AddIndex(
            model_name="saasauthauditevent",
            index=models.Index(
                fields=["actor_user", "created_at"], name="memberships_actor_u_4920ce_idx"
            ),
        ),
    ]
