# Generated by Django 5.2.10 on 2026-01-22 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('cash', 'Liquidez'), ('investments', 'Inversiones'), ('real_estate', 'Inmuebles'), ('vehicle', 'Vehículo'), ('other', 'Otros')], default='cash', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='net_worth_a_user_id_16359c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('mortgage', 'Hipoteca'), ('personal_loan', 'Préstamo personal'), ('credit_card', 'Tarjeta'), ('other', 'Otros')], default='other', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='net_worth_l_user_id_91f0e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worth_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'snapshot_date'], name='net_worth_n_user_id_884495_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'snapshot_date'), name='unique_snapshot_per_user_and_date')],
            },
        ),
    ]
