# Generated by Django 5.2.10 on 2026-01-23 21:40

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_worth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='liability',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='asset',
            name='accounting_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='tracking_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('accounting', 'Desde contabilidad')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='liability',
            name='accounting_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='liability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='tracking_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('accounting', 'Desde contabilidad')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='asset',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Valor actual (positivo). Si tracking_mode=accounting, este campo puede ignorarse en summary.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='liability',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Deuda pendiente (positiva). Si tracking_mode=accounting, este campo puede ignorarse en summary.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', 'is_active'], name='net_worth_a_user_id_f7c46e_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', 'tracking_mode'], name='net_worth_a_user_id_e93eae_idx'),
        ),
        migrations.AddIndex(
            model_name='liability',
            index=models.Index(fields=['user', 'is_active'], name='net_worth_l_user_id_c8ee1c_idx'),
        ),
        migrations.AddIndex(
            model_name='liability',
            index=models.Index(fields=['user', 'tracking_mode'], name='net_worth_l_user_id_fac304_idx'),
        ),
    ]
