# Generated by Django 5.2.10 on 2026-01-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_worth', '0002_alter_asset_options_alter_liability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networthsnapshot',
            name='base_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
