# Generated by Django 5.2.10 on 2026-01-28 21:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_worth', '0003_networthsnapshot_base_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('adult', 'Adulto'), ('child', 'Niño')], default='adult', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('individual', 'Individual'), ('shared', 'Compartido')], max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_ownerships', to='net_worth.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='ownership',
            field=models.ForeignKey(blank=True, help_text='Titularidad (individual o compartido)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='net_worth.ownership'),
        ),
        migrations.AddField(
            model_name='liability',
            name='ownership',
            field=models.ForeignKey(blank=True, help_text='Titularidad (individual o compartido)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liabilities', to='net_worth.ownership'),
        ),
        migrations.CreateModel(
            name='OwnershipSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_splits', to='net_worth.familymember')),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='net_worth.ownership')),
            ],
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['user', 'is_active'], name='net_worth_f_user_id_53564e_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['user', 'role'], name='net_worth_f_user_id_b64566_idx'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_member_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='ownership',
            index=models.Index(fields=['user', 'kind'], name='net_worth_o_user_id_fb61e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'individual'), ('member__isnull', False)), models.Q(('kind', 'shared'), ('member__isnull', True)), _connector='OR'), name='ownership_individual_requires_member'),
        ),
        migrations.AddConstraint(
            model_name='ownershipsplit',
            constraint=models.UniqueConstraint(fields=('ownership', 'member'), name='uniq_split_member_per_ownership'),
        ),
    ]
