# Generated by Django 5.2.10 on 2026-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_worth', '0006_alter_asset_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability',
            name='is_asset_backed',
            field=models.BooleanField(default=False, help_text='True si esta deuda está asociada a un activo (hipoteca, préstamo coche, etc.). False si es deuda de gasto/consumo (clínica, tarjeta, etc.).'),
        ),
    ]
