# Generated by Django 5.2.10 on 2026-02-04 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_worth', '0007_liability_is_asset_backed'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability',
            name='financed_asset',
            field=models.ForeignKey(blank=True, help_text='Activo que financia esta deuda (si aplica). Si es null, es deuda sin activo asociado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_liabilities', to='net_worth.asset'),
        ),
    ]
