# Generated by Django 6.0.7 on 2026-07-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saas_access", "0001_adopt_existing_saas_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="saasaccessprofile",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
