# Generated by Django 6.0.7 on 2026-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saas_access", "0002_saasaccessprofile_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaasLoginThrottleState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username_hash", models.CharField(max_length=64, unique=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("first_failed_at", models.DateTimeField()),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "memberships_saasloginthrottlestate",
            },
        ),
    ]
