# Generated by Django 5.2.10 on 2026-01-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_fxrate_core_fxrate_from_cu_677796_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InflationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('ES', 'España')], default='ES', max_length=10)),
                ('period', models.DateField(help_text='Mes del índice (usar YYYY-MM-01)')),
                ('index', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['region', 'period'], name='core_inflat_region_fff855_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'period'), name='unique_inflation_region_period')],
            },
        ),
    ]
